Controllers/DatabaseController.cs
using System;
using System.Diagnostics;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppVsCode.Models;

namespace AppVsCode.Controllers
{
    public class DatabaseController : Controller
    {
        private readonly Database _context;
        public DatabaseController(Database context)
        {
            _context = context;
        }

        #region Index

        // GET: Movies
        // public IActionResult Index()
        public async Task<IActionResult> Index()
        {
            return View(await _context.Posts.ToListAsync());

            // Appelle l'action du controller.
                // return RedirectToAction("Test");
        }

        #endregion

        #region Details

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .FirstOrDefaultAsync(p => p.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        #endregion

        #region Create

        // GET: Movies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Content,PostDate")] Post post)
        {
            if (ModelState.IsValid)
            {
                if(post.PostDate == DateTime.MinValue)
                    post.PostDate = DateTime.Now;

                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        #endregion

        #region Edit

        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Content,PostDate")] Post post)
        {
            if (id != post.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        #endregion

        #region Delete

        // GET: Movies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var post = await _context.Posts.FindAsync(id);
            _context.Posts.Remove(post);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        #endregion

        #region Exist
        private bool PostExists(int id)
        {
            return _context.Posts.Any(e => e.Id == id);
        }

        #endregion
    
        #region Test

        public IActionResult Test()
        {

                        
            return View();
        }

        public void GetTablesOfDB()
        {
            // Code pour récupérer la liste des tables de la base de de données.
            var command = _context.Database.GetDbConnection().CreateCommand();
            command.CommandText = "SELECT name from sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' OR '_%'";
            
            _context.Database.OpenConnection();
            using (var result = command.ExecuteReader()) 
            {
                while (result.Read())
                {
                    Console.WriteLine(result.GetString(0));
                    Console.WriteLine(result.GetType());
                }
            }

            // Tester pour récupérer les tables de la DB
            // DbTransaction MyTransit = _context.Database.ExecuteSqlRaw("MA REQUETE SQL");
            // _context.Database.UseTransaction(MyTransit);
        }

        #endregion

    }
}

Controllers/DemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AppVsCode.Controllers
{
    public class DemoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult Bootstrap()
        {
            ViewBag.Message = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Est cupiditate adipisci nulla ullam accusantium facere iste itaque eaque unde modi a illo error, repellendus officia quaerat minima accusamus vero? Aliquam!";
            return View();
        }

        public IActionResult Razor()
        {
            ViewBag.Messag = "Message du ViewBag";
            
            #region ViewData

            ViewData["Message"] = "Message du ViewData";
            // Ou
            // ViewData.Add("Prénom", "Bill");

            #endregion

            return View();
        }
    }
}

Controllers/ToolsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AppVsCode.Models;
using AppVsCode.Core;

namespace AppVsCode.Controllers
{
    public class ToolsController : Controller
    {
        public IActionResult Index()
        {
            Post monPost = new Post
            {
                Id = 3,
                Title = MyFirstHelper.MyFirstFunc(),
                Content = "MonContenu",
                PostDate = DateTime.Now
            };

                      
            
            return View(monPost);
        }

        public ActionResult Afficher()
        {
            string maString = "Afficher un string";
            return PartialView(maString);
        }
            }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppVsCode</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppVsCode</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Demo" asp-action="Index">Demo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tools" asp-action="Index">Tools</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Database" asp-action="Index">Database</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - AppVsCode
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MyPartial.cshtml
@for (int i = 0; i < 10; i++)
{
    <p>@ViewData["id"]</p>
    <p><strong>RENOCK</strong></p>
}

@functions {
    public int MyProperty { get; set; }
}